name: CI Pipeline

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  plan:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: iac
    steps:
    - uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.1.9

    - name: Setup GCP Credentials
      run: echo '${{ secrets.GCP_CREDENTIALS }}' > gcp-credentials.json
      env:
        GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}

    - name: Terraform Init
      run: terraform init
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/iac/gcp-credentials.json

    - name: Terraform Plan
      run: terraform plan
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/iac/gcp-credentials.json

  apply:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: iac
    steps:
    - uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.1.9

    - name: Setup GCP Credentials
      run: echo '${{ secrets.GCP_CREDENTIALS }}' > gcp-credentials.json
      env:
        GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}

    - name: Terraform Init
      run: terraform init
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/iac/gcp-credentials.json

    - name: Terraform Apply
      run: terraform apply -auto-approve
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/iac/gcp-credentials.json
